strictness: veryhigh
doc-warnings: true
member-warnings: true
ignore-paths:
  - tests
mypy:
  run: true
  options:
    ignore-missing-imports: true
pep257:
  disable:
    - D203  # Don't require blank line before class docstrings
    - D213  # Don't require summaries to start on the second line
    - D107  # Don't require a docstring on __init__
pylint:
  run: false  # pylint is currently useless with Python 3.7, way too
              # many false positives
  disable:
    - wrong-import-order  # at least until dataclasses get recognized
    - too-many-instance-attributes
    - too-few-public-methods
    - unsubscriptable-object
    - unsupported-membership-test
  options:
    good-names: _,i,j,k,v,e,db,fn,fp,log,id
pyflakes:
  run: false
mccabe:
  run: false
