version: '2'
services:
  webapp:
    environment:
      PRODUCTION: 'true'
      SERVER_NAME:
      PREFERRED_URL_SCHEME:
      SECRET_KEY:
    command: 'gunicorn -w 4 -b 0.0.0.0:5000 app:app'
  worker:
    environment:
      PRODUCTION: 'true'
      SERVER_NAME:
      PREFERRED_URL_SCHEME:
      SECRET_KEY:
