version: '2'

volumes:
  database:
    external: true
  queue:
    external: true

services:
  postgres:
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    volumes:
      - queue:/data
  webapp:
    environment:
      PRODUCTION: 'true'
      SERVER_NAME:
      PREFERRED_URL_SCHEME:
      SECRET_KEY:
    command: 'gunicorn --worker-class gevent -w 4 -b 0.0.0.0:5000 manage:app'
  worker:
    environment:
      PRODUCTION: 'true'
      SERVER_NAME:
      PREFERRED_URL_SCHEME:
      SECRET_KEY:
